version: 1
policies:
  - id: cf-autotick-bot-test-package-policy
    repo: cf-autotick-bot-test-package-feedstock
    teams:
      - core
    pull_request: false
  - id: cirun-feedstock-policy
    repo: cirun-feedstock
    roles:
      - admin
    pull_request: false
  - id: sandbox-public-policy
    repo: sandbox-public
    teams:
      - core
    pull_request: false
  - id: conda-forge-users-example-policy
    repo: conda-forge-users-example
    users:
      - aktech
    pull_request: false
  - id: conda-forge-role-example-policy
    repo: conda-forge-role-example
    roles:
      - admin
    pull_request: false
  - id: conda-forge-users-from-json-policy
    repo: conda-forge-users-from-json
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
    pull_request: false
access_control:
  - resource: cirun-openstack-gpu-large
    policies:
      - cf-autotick-bot-test-package-policy
      - sandbox-public-policy
      - conda-forge-users-example-policy
      - conda-forge-users-from-json-policy
      - conda-forge-role-example-policy

  - resource: cirun-openstack-cpu-medium
    policies:
      - cirun-feedstock-policy
      - sandbox-public-policy
      - conda-forge-users-example-policy
      - conda-forge-users-from-json-policy
      - conda-forge-role-example-policy
