version: 1
policies:
  - id: cirun-sandbox-policy
    repo: cirun-sandbox
    teams:
      - core
      - alpha
      - beta
    pull_request: true
  - id: cirun-demo-repo-policy
    repo: cirun-demo
    teams:
      - core
      - alpha
      - beta
    pull_request: true
  - id: cirun-demo-policy
    repo: cirun-demo
    teams:
      - alpha
    pull_request: true
  - id: aktech/sandbox-policy
    repo: aktech/sandbox
    teams:
      - core
      - alpha
      - beta
    pull_request: true
  - id: cirun-feedstock-policy
    repo: cirun-feedstock
    teams:
      - cirun-feedstock
    pull_request: null
access_control:
  - resource: aws-gpu-runner
    policies:
      - cirun-demo-repo-policy
  - resource: aws-cpu-runner-fail
    policies:
      - cirun-demo-repo-policy
  - resource: aws-cpu-runner-pass
    policies:
      - cirun-demo-repo-policy
  - resource: aws-cpu-runner-fail-2
    policies:
      - cirun-demo-repo-policy
  - resource: aws-cpu-arm-runner
    policies:
      - cirun-demo-repo-policy
  - resource: aws-cpu-different-region
    policies:
      - cirun-demo-repo-policy
  - resource: aws-labels-runner
    policies:
      - cirun-demo-repo-policy
  - resource: aws-multiple-runner
    policies:
      - cirun-demo-repo-policy
  - resource: gcp-gpu-custom-machine-runner
    policies:
      - cirun-demo-repo-policy
  - resource: gcp-cpu-runner
    policies:
      - cirun-demo-repo-policy
  - resource: do-runner
    policies:
      - cirun-demo-repo-policy
  - resource: azure-cpu-runner
    policies:
      - cirun-demo-repo-policy
  - resource: azure-gpu-runner
    policies:
      - cirun-demo-repo-policy
  - resource: azure-cpu-runner-spotinstance
    policies:
      - cirun-demo-repo-policy
  - resource: oracle-runner
    policies:
      - cirun-demo-repo-policy
  - resource: aws-runner-1
    policies: []
  - resource: aws-runner-2
    policies: []
  - resource: amit-resource
    policies: []
  - resource: jaime-resource
    policies: []
  - resource: c
    policies:
      - cirun-feedstock-policy
  - resource: i
    policies:
      - cirun-feedstock-policy
  - resource: r
    policies:
      - cirun-feedstock-policy
  - resource: u
    policies:
      - cirun-feedstock-policy
  - resource: n
    policies:
      - cirun-feedstock-policy
  - resource: '-'
    policies:
      - cirun-feedstock-policy
  - resource: g
    policies:
      - cirun-feedstock-policy
  - resource: p
    policies:
      - cirun-feedstock-policy
  - resource: e
    policies:
      - cirun-feedstock-policy
