# Self-Hosted Github Action Runners on Openstack via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml
runners:
  - name: cirun-openstack-gpu-large
    # Cloud Provider: Openstack
    cloud: openstack
    # Instance type refers to flavors in openstack
    instance_type: gpu_large
    # The machine image to use for creating VM
    machine_image: ubuntu-2204-nvidia-20230914
    region: RegionOne
    labels:
      - cirun-openstack-gpu-large

  - name: cirun-openstack-cpu-medium
    # Cloud Provider: Openstack
    cloud: openstack
    # Instance type refers to flavors in openstack
    instance_type: ci_medium
    # The machine image to use for creating VM
    machine_image: ubuntu-2204-cloud-jammy-20221104
    region: RegionOne
    labels:
      - cirun-openstack-cpu-medium

  - name: aws-cpu-runner
    cloud: aws
    instance_type: t2.small
    machine_image: ami-06fd8a495a537da8b
    labels:
      - cirun-aws-cpu-runner

setup_info:
  - group: Alpha
    detail: This is some information that will be shown in the first step of the github actions job.

  - group: Beta
    detail: >
      Some text for beta
      this is multiline text
      that will also be shown in the
      first step of the github actions job called Setup Info

  - group: Gamma
    detail: Some text for gamma with link: https://cirun.io
